alpastor/alpastor/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from accounts import views as accounts_views
from quiz import views as quiz_views
from epita import views
from epita import csv_views
from epita.views import (
    CourseView, ScheduleView, AttendanceView, GetStudentAttendanceData,
    OverrideStudentAttendanceData, ToggleAttendanceLock, AccountUpdateView, CheckAttendanceByUser)
from graphs import views as graphs_views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

# add new URL to this structure in alpastor/urls.py


urlpatterns = [
    path('', views.dashboard, name='home'),

    # Attendance
    path('attendance/course/<slug:slug>/schedule/update', login_required(GetStudentAttendanceData.as_view()), name='update_attendance'),
    path('attendance/course/<slug:slug>/schedule/manualoverride', login_required(OverrideStudentAttendanceData.as_view()), name='override_attendance'),
    path('attendance/course/<slug:slug>/schedule/check/<str:token>', CheckAttendanceByUser, name='check_attendance'),
    path('attendance/course/<slug:slug>/schedule/togglelock', login_required(ToggleAttendanceLock.as_view()), name='toggle_attendance_lock'),
    path('attendance/course/<slug:slug>/schedule/', login_required(AttendanceView.as_view()), name='attendance_list'),
    path('attendance/course/<slug:slug>', login_required(ScheduleView.as_view()), name='schedule_list'),
    path('attendance/', login_required(CourseView.as_view()), name='course_list'),

    # graphs
    path('graphs/', login_required(graphs_views.AttendanceGraphs.as_view()), name='graphs'),

    # Accounts, change
    path('account_update/', AccountUpdateView.as_view(), name='account_update'),

    # People
    path('people/', views.people, name='people'),

    # CSV
    path('csv/student/', csrf_exempt(login_required(csv_views.StudentToCSVView.as_view())), name='studentcsv'),

    # Quiz paths
    path('quiz/quiz_builder/savenewquiz/', login_required(quiz_views.SaveNewQuiz.as_view()), name='savenewquiz'),
    path('quiz/quiz_builder/getquiz/', login_required(quiz_views.GetQuizData.as_view()), name='existingquestion'),
    path('quiz/quiz_builder/', login_required(quiz_views.QuizBuilderView.as_view()), name='quizbuilder'),
    path('quiz/', quiz_views.quizHomePage, name='quiz_home_page'),
    path('quiz/', quiz_views.delete, name='delete_view'),

     # Password Reset
    path('generatereset/', accounts_views.GenerateResetToken.as_view(), name='genreset'),
    path('resetpass/<str:token>/', accounts_views.ResetPassword.as_view(), name='resetpass'),

    # Admin/Superuser
    path('login/', accounts_views.login, name='login'),
    path('manageusers/processusercsv/', login_required(accounts_views.ProcessUserCSVData.as_view()), name='processusercsv'),
    path('manageusers/savenewusers/', login_required(accounts_views.SaveNewUsers.as_view()), name='savenewusers'),
    path('manageusers/addstudentcourse/', login_required(accounts_views.AddStudentCourse.as_view()), name='addstudentcourse'),
    path('manageusers/savenewcourse/', login_required(accounts_views.SaveNewCourse.as_view()), name='addstudentcourse'),
    path('manageusers/deletestudentcourse/', login_required(accounts_views.DeleteStudentCourse.as_view()), name='deletestudentcourse'),
    path('manageusers/', login_required(accounts_views.manageusers), name='manageusers'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('admin/', admin.site.urls),

]

urlpatterns = format_suffix_patterns(urlpatterns)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alpastor/epita/models.py
from django.db import models
from alpastor import settings
from accounts.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_countries.fields import CountryField
import re
import datetime
from django.utils import timezone
from django.utils.timezone import now

def choice_to_string(choices, index):
    return [x[1] for x in choices][index]

def string_to_choice(choices, val):
    for x in choices:
        if x[1] == val:
            return x[0]

@receiver(post_save, sender=User)
def create_user_student_or_prof(sender, instance, created, **kwargs):
    """
    Automatically creates a record of student/professor, depending on is_staff bool

    This is a signal-function, meaning it gets fired on the 'post_save' signal

    :param sender:      User model instance (from accounts/models.py)
    :param instance:    The instance of the created User
    :param created:     Boolean indicating whether User was successfully created
    :param kwargs:      Additional keyword args
    :return:            None
    """
    if created:
        if not instance.is_staff:
            Student.objects.create(user=instance)
        elif not instance.is_superuser:
            Professor.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_student(sender, instance, **kwargs):
    """
    Automatically saves/stores a record of student/professor, depending on is_staff bool

    This is a signal-function, meaning it gets fired on the 'post_save' signal
    :param sender:      User model instance (from accounts/models.py)
    :param instance:    The instance of the created User
    :param kwargs:      Additional keyword args
    :return:            None
    """
    if not instance.is_staff:
        instance.student.save()
    elif not instance.is_superuser:
        instance.professor.save()

def photo_file_path(instance, filename):
    return "photos/{0}_{1}_{2}".format(instance.id, instance.user.get_full_name().replace(' ', '_'), filename)

class Student(models.Model):
    """
    Defines the Student database table

    Args:
        user = FK to User table (containing email and names)
        phone = phone number, in string form, to allow international + symbols
        program = student's overall program (ME, MSc)
        specialization = student's sub specialty (Software Engineering, ISM, etc.)
        intakeSemester = class that student joined, form of Season Year (Fall 2017, Spring 2016)
        country = country of origin for the student
        city = city of origin for the student
        languages = which languages the student speaks, comma separated (English,French)
        photo_location = path on server to the stored location of the student's photo
    """

    NONE = 0

    # Programs
    ME = 1
    MSc = 2
    FGITM = 3
    EXCHANGE = 4

    PROGRAM_CHOICES = [
        (NONE, 'None'),
        (ME, 'Master of Engineering'),
        (MSc, 'Master of Science'),
        (FGITM, 'Global IT Management (French)'),
        (EXCHANGE, "Exchange"),
    ]

    # Specializations
    SE = 1
    ISM = 2
    DSA = 3
    CS = 4
    SDM = 5
    SDS = 6
    IGITM = 7
    AI = 8

    SPECIALIZATION_CHOICES = [
        (NONE, 'None'),
        (SE, 'Software Engineering'),
        (ISM, 'Information Systems Management'),
        (DSA, 'Data Science and Analytics'),
        (CS, 'Computer Security'),
        (SDM, 'Software Development and Multimedia'),
        (SDS, 'Systems Networks and Security'),
        (IGITM, 'Global IT Management (International)'),
        (AI, "Artificial Intelligence"),
    ]

    # Enrollment status
    ENROLLED = 0
    WITHDRAWN = 1
    EXPELLED = 2
    GRADUATED = 3

    ENROLLMENT_CHOICES = [
        (ENROLLED, 'Enrolled'),
        (WITHDRAWN, 'Withdrawn'),
        (EXPELLED, 'Expelled'),
        (GRADUATED, 'Graduated'),
    ]

    # Additional Flags
    OK = 0
    ACADEMIC_WARNING = 1
    ATTENDANCE_WARNING = 2

    ADDITIONAL_FLAGS = [
        (OK, "OK"),
        (ACADEMIC_WARNING, "Academic warning"),
        (ATTENDANCE_WARNING, "Attendance warning"),
    ]

    # Seasons
    WINTER = 0
    SPRING = 1
    SUMMER = 2
    FALL = 3

    SEASON_CHOICES = [
        (WINTER, "Winter"),
        (SPRING, "Spring"),
        (SUMMER, "Summer"),
        (FALL, "Fall"),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=31, blank=True, null=True)
    program = models.IntegerField(choices=PROGRAM_CHOICES, default=NONE, blank=False)
    specialization = models.IntegerField(choices=SPECIALIZATION_CHOICES, default=NONE, blank=False)
    intake_season = models.IntegerField(choices=SEASON_CHOICES, default=FALL, blank=False)
    intake_year = models.IntegerField(blank=False, default=now().year)
    country = CountryField(help_text="country", blank_label="Select a country", countries_flag_url="flags/{code}.jpg")
    city = models.CharField(max_length=127, blank=True)
    languages = models.CharField(max_length=127, blank=True)
    photo = models.ImageField(null=True, blank=True, upload_to=photo_file_path)
    address_street = models.CharField(max_length=255, null=True, blank=True)
    address_city = models.CharField(max_length=255, null=True, blank=True)
    address_misc = models.CharField(max_length=255, null=True, blank=True)
    postal_code = models.IntegerField(blank=True, null=True)
    dob = models.DateField(null=True, blank=True, verbose_name="Date of Birth")
    enrollment_status = models.IntegerField(choices=ENROLLMENT_CHOICES, default=ENROLLED, blank=False)
    flags = models.IntegerField(choices=ADDITIONAL_FLAGS, default=OK, blank=False)

    def __repr__(self):
        return "Student(first_name={}, last_name={}, external_email={}, epita_email={}, phone={}, program={}, " \
               "specialization={}, intake_season={}, intake_year={}, country={}, city={}, languages={}, photo_location={}" \
               ")".format(self.user.first_name, self.user.last_name, self.user.external_email, self.user.email, self.phone,
                          self.program, self.specialization, self.intake_season, self.intake_year, self.country.name, self.city,
                          self.languages, self.photo.name)

    def __str__(self):
        return self.user.get_full_name()

    def student_email(self):
        return self.user.email

    def country_name(self):
        return self.country.name

class Professor(models.Model):
    """
    Defines the Professor database table

    Args:
        user = FK to User table (containing email and names)
        phone = phone number, in string form, to allow international + symbols
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=31)
    photo = models.ImageField(blank=True, upload_to=photo_file_path)

    def __repr__(self):
        return "Professor(first_name={}, last_name={}, external_email={}, epita_email={}, phone={})".format(
            self.user.first_name, self.user.last_name, self.user.external_email, self.user.email, self.phone)

    def __str__(self):
        return "{} {}".format(self.user.first_name, self.user.last_name)

    def professor_email(self):
        return self.user.email


class Course(models.Model):
    """
    Defines the Course database table

    Args:
        professor_id = FK to the Professor table, indicating who is teaching it
        title = title of the course
        description = fuller description of the course
        semester_season = the semester season in which the course will be taught (Spring)
        semester_year = the semester year in which the course will be taught (2020)
        module = the grading module that this course falls under (Technical, Business, etc)
        credits = the number of credits that will be offered for this course

    Note:
         columns 'title' and 'semester_year' and 'semester_season' must be unique as a pair, meaning you cannot have the same course title
         during the same semester (year + season)
    """
    class Meta:
        unique_together = (('title', 'semester_season', 'semester_year'),)

    professor_id = models.ForeignKey(Professor, on_delete=models.CASCADE, blank=True)
    code = models.CharField(max_length=127, blank=True, help_text="Course code e.g. ADVC123123", null=True)
    title = models.CharField(max_length=127, help_text="Course title")
    description = models.TextField(max_length=1000, blank=True, help_text="Course description")
    semester_season = models.IntegerField(choices=Student.SEASON_CHOICES)
    semester_year = models.IntegerField(blank=False, default=now().year)
    module = models.CharField(max_length=63, null=True, blank=True, help_text="Module or teaching unit")
    credits = models.IntegerField(null=True, blank=True)
    hours = models.IntegerField(null=True, blank=True)
    slug = models.SlugField(max_length=158, blank=False, default='course-slug')

    def clean(self):
        super(Course, self).clean()

        # Reduce unnecessary spacing
        self.title = re.sub(' +', ' ', self.title)

        # Save slug field (e.g. fall-2019-advanced-c-programming
        slug_season = choice_to_string(Student.SEASON_CHOICES, self.semester_season)
        self.slug = slug_season.lower() + '-' + str(self.semester_year) + '-' + self.title.lower().replace(' ', '-')

    def save(self, **kwargs):
        self.full_clean()
        super(Course, self).save()

    def __repr__(self):
        return "Course(professor_id={}, title={}, description={}, full_semester={}, module={}, credits={})".format(
            self.professor_id, self.title, self.description, self.full_semester(), self.module, self.credits)

    def __str__(self):
        return "{}".format(self.title)

    def verbose_title(self):
        return "{} ({})".format(self.title, self.full_semester())

    def full_semester(self):

alpastor/accounts/forms.py
from django import forms
from django.contrib.auth import authenticate
from accounts.models import User as CustomUser


class LoginForm(forms.Form):
    username = forms.EmailField(max_length=255, help_text="Must be your epita-issued email address", required=True,
                             widget=forms.TextInput(attrs={
                                 'placeholder': "yourname@epita.fr",
                             }))
    password = forms.CharField(max_length=255, required=True,
                               widget=forms.PasswordInput(attrs={
                                   'placeholder': 'examplepass',
                               }))

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        self.user_cache = authenticate(username=username, password=password)
        if not self.user_cache:
            raise forms.ValidationError("Login was invalid, either wrong password or not such email")
        elif not self.user_cache.is_active:
            raise forms.ValidationError("User is no longer active")
        elif not self.user_cache.is_registered:
            raise forms.ValidationError("User is not yet registered")
        return self.cleaned_data

    def get_user(self):
        return self.user_cache


class CustomUserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ('email', 'first_name', 'last_name', 'external_email', 'is_active', 'is_staff', 'is_superuser')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and (password1 != password2):
            raise forms.ValidationError("Passwords do not match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class CustomUserChangeForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['email', 'password', 'first_name', 'last_name', 'external_email', 'is_active', 'is_staff',
                  'is_superuser']



class ResetPasswordForm(forms.Form):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={
        'class': 'form-control',
    }))
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput(attrs={
        'class': 'form-control',
    }))

    def clean(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if not password1 or not password2:
            raise forms.ValidationError("Must fill both passwords")

        if password1 and password2 and (password1 != password2):
            raise forms.ValidationError("Passwords do not match")

    def save(self, **kwargs):
        user = kwargs['user']
        if not user:
            raise forms.ValidationError("user does not exist")

        try:
            self.full_clean()
        except forms.ValidationError:
            raise forms.ValidationError("could not clean the data in form")

        new_password = self.cleaned_data['password1']

        user.set_password(new_password)
        user.set_registered()
        user.save()

alpastor/templates/epita/accounts.html
{% extends 'base_generic.html' %}

{% load static %}

{% block additional_links %}
    <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block content %}
    <div class="card-body container-fluid">
        <div class="row">
            <div class="add-single-user-form col-8">
                {% if request.user.is_staff == False %}
                    {% if student.photo %}
                        <img class="user-photo" src="{{ student.photo.url }}">
                        <br>
                    {% endif %}
                    <label for="first_name">First names:</label>
                    <input class="input-group" type="text" id="first_name" name="first_name" disabled="True" placeholder="{{ student.user.first_name }}" value="{{ student.user.first_name }}">

                    <label for="last_name">Last name:</label>
                    <input class="input-group" type="text" id="last_name" name="last_name" disabled="True" placeholder="{{ student.user.last_name }}" value="{{ student.user.last_name }}">

                    <label for="program">Program:</label><br>
                    <input class="input-group" type="text" id="program" name="program" placeholder="{{ student.get_program_display }}" value="{{ student.get_program_display }}" disabled="True">

                    <label for="specialization">Specialization:</label><br>
                    <input class="input-group" type="text" id="specialization" name="specialization" placeholder="{{ student.get_specialization_display }}" value="{{ student.get_specialization_display }}" disabled="True">

                    <label for="intake-season">Intake Season:</label><br>
                    <input class="input-group" type="text" id="intake-season" name="intake-season" placeholder="{{ student.get_intake_season_display }}" value="{{ student.get_intake_season_display }}" disabled="True">

                    <label for="intake-year">Intake Year:</label><br>
                    <input class="input-group" type="text" id="intake-year" name="intake-year" placeholder="{{ student.intake_year }}" value="{{ student.intake_year }}" disabled="True">


                {% endif %}
                {% if request.user.is_staff == True %}
                    <label for="first_name">First names:</label>
                    <input class="input-group" type="text" id="first_name" name="first_name" disabled="True" placeholder="{{ professor.user.first_name }}" value="{{ professor.user.first_name }}">

                    <label for="last_name">Last name:</label>
                    <input class="input-group" type="text" id="last_name" name="last_name" disabled="True" placeholder="{{ professor.user.last_name }}" value="{{ professor.user.last_name }}">
                {% endif %}
                <form class="update-student" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form }}
                    <div style="text-align: center;">
                        <br>
                        <button class="btn btn-info" type="submit" value="OK"> Update</button>
                    </div>
                    {#                </div>#}
                </form>

            </div>
        </div>

    </div>
    {% comment %}
        <div class="row">
            <div class="col-6">
                <label>Professor</label><br> onclick="updateStudentInfo();" enctype="multipart/form-data"
                <input type="radio" name="staff" value="professor" onchange="toggleStudentForm(this)" checked="checked">
            </div>
            <div class="col-6">
                <label>Student</label><br>
                <input type="radio" name="staff" value="student" onchange="toggleStudentForm(this);">
            </div>
        </div>
    {% endcomment %}
    {% comment %}    <script type="application/javascript">
        function updateStudentInfo() {
            let data = new FormData();

            $.ajax({
                type: "POST",
                enctype: 'multipart/form-data',
                //url: window.location.origin + window.location.pathname + "processusercsv/",
                url: window.location.origin + window.location.pathname,
                data: data,
                processData: false,
                contentType: false,
                cache: false,
                timeout: 600000,
                success: function () {
                    console.log("Update works");
                },
                error: function (e) {
                    console.log("ERROR : ", e);
                }
            });
        }

    </script>{% endcomment %}

{% endblock %}

alpastor/templates/epita/attendance_list.html
{% extends 'base_generic.html' %}

{% load static %}

{% block content %}
    <table class="table table-striped">
        <thead>
        <th class="text-center">Photo</th>
        <th class="text-center">Student Name</th>
        <th class="text-center">Status</th>
        <th class="text-center">Supporting Documents</th>
        <link href="{% static 'css/attendance.css' %}" rel="stylesheet">
        </thead>
        <tbody>
        {% for form_item in form %}
            <form id="rGroup1" class="form-group" method="post" enctype="multipart/form-data">{% csrf_token %}
                    <tr>
                        <td>
                            {% if form_item.student_id.photo != None %}
                                {% with 'image/portraits/'|add:form_item.student_id.photo as image_static %}
                                    <img src="{% static image_static %}" alt={{ form_item.student_id.user }}>
                                {% endwith %}
                            {% else %}
                                <img src="{% static 'image/portraits/generic_avatar.jpg' %}" alt="Default Avatar"
                                     class="people-img">
                            {% endif %}
                        </td>
                        <td>
                            {{ form_item.instance.student_id }}
                            {{ form_item.student_id.as_hidden }}
                            {{ form_item.schedule_id.as_hidden }}
                            <input name="id" value="{{ form_item.instance.id }}" type="hidden">
                        </td>
                        <td>
                            {{ form_item.status }}
                        </td>
                        <td>
                            {{ form_item.file_upload }}
                            <input type="submit">
                        </td>
                    </tr>
            </form>
        {% endfor %}
        </tbody>
    </table>
    <script>
        function disableButton() {
            var auxRadio = document.getElementById("rGroup1");
            var aux = document.getElementById("uploadForm");
            if (auxRadio.elements["status"].value === "3") {
                aux.disabled = false;
            } else {
                aux.disabled = true;
            }
        }
    </script>
{% endblock %}

alpastor/templates/epita/attendance_prof.html
{% extends 'base_generic.html' %}

{% load static %}

<!-- Adding additional css/js links -->
{% block additional_links %}
    <link rel="stylesheet" href="{% static 'css/attendance_prof.css' %}">
    <script src="{% static 'js/attendance.js' %}"></script>
{% endblock %}

<!-- Page content -->
{% block content %}

    <div class="attendance-container text-center">

        <div class="title-container">
            <h1>{{ schedule.course_id }}</h1>
            <h3>{{ schedule.date }}</h3>
            <h5>{{ schedule.start_time|time:"H:i" }} - {{ schedule.end_time|time:"H:i" }}</h5>
        </div>

        {% if schedule.attendance_closed %}
            <button class="lock-attendance locked btn btn-info" onclick="toggleAttendanceLock();">Locked <i
                    class="lock-icon fa fa-lock"></i></button>
        {% else %}
            <button class="lock-attendance unlocked btn btn-info" onclick="toggleAttendanceLock();">Unlocked <i
                    class="lock-icon fa fa-unlock"></i></button>
        {% endif %}

        <div class="btn-group btn-group-toggle btn-group-view" data-toggle="buttons">
            <label class="btn btn-portraits active">
                <input type="radio" name="options" autocomplete="off" onchange='changeView(ViewEnum.portraits);'>
                Portraits
            </label>
            <label class="btn btn-names">
                <input type="radio" name="options" autocomplete="off" onchange='changeView(ViewEnum.names);'> Names
            </label>
        </div>

        <button class="btn btn-info" onclick="dispatchStatusChangesToDatabase();">Submit all changes</button>

        <div class="status-container">
            <div class="progress">
                <div id="progress-present" class="progress-bar progress-bar-striped bg-success" role="progressbar"
                     aria-valuemin="0"></div>
                <div id="progress-excused" class="progress-bar progress-bar-striped bg-warning" role="progressbar"
                     aria-valuemin="0"></div>
                <div id="progress-absent" class="progress-bar progress-bar-striped bg-danger" role="progressbar"
                     aria-valuemin="0"></div>
            </div>
            <div class="row">
                <div id="stats-present" class="col-3"></div>
                <div id="stats-excused" class="col-3"></div>
                <div id="stats-absent" class="col-3"></div>
                <div id="stats-total" class="col-3"></div>
            </div>
        </div>


        {#        <button class="override-submit btn btn-info" onclick="dispatchStatusChangesToDatabase();">Submit all changes</button>#}

        <div class="student-view-container container-fluid">
            <!-- These divs will be filled via ajax calls -->
            <div class="present-container row">
            </div>

            <div class="excused-container row">
            </div>

            <div class="absent-container row">
            </div>
        </div>
    </div>

    <script>
        window.onload = getAttendanceData()();

        let attendanceInterval = 0;

        {% if not schedule.attendance_closed %}
            attendanceInterval = setInterval(getAttendanceData(), 10000);
        {% endif %}

        function toggleAttendanceLock() {
            let locked = true;

            clearInterval(attendanceInterval);

            button = $('.lock-attendance');

            if (button.hasClass('unlocked')) {
                // change to locked
                button.html("Locked <i class=\"lock-icon fa fa-lock\"></i>");
                locked = true;
            } else {
                // change to unlocked
                button.html("Unlocked <i class=\"lock-icon fa fa-unlock\"></i>");

                // Restart interval
                attendanceInterval = setInterval(getAttendanceData(), 10000);
                locked = false;
            }

            button.toggleClass('locked unlocked');

            let baseUrl = window.location.origin + window.location.pathname + "togglelock";

            $.ajax({
                type: "POST",
                url: baseUrl,

                data: {
                    schedule_id: parseGET()['schedule_id'],
                    lock_status: locked
                },

                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (data) {
                    console.log("success");
                },
                failure: function (errMsg) {
                    console.log(errMsg);
                }
            });
        }
    </script>

{% endblock %}

alpastor/templates/epita/course_list.html
{% extends 'base_generic.html' %}

{% load static %}

{% block additional_links %}
    <link href="{% static 'css/course_list.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

    <div class="accordion-container container">
        <div id="accordion" class="center-container">
            {% for semester, course_list in semester_list.items %}
                <div class="card">

                    <div class="card-header" id="headingOne">
                        <button class="header-btn btn btn-block" data-toggle="collapse" data-target="#{{ semester }}" aria-expanded="false" aria-controls="{{ semester }}">
                            <h5 class="mb-0">
                                {{ semester }}
                            </h5>
                        </button>
                    </div>

                    <div id="{{ semester }}" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">

                        {%  for course in course_list %}

                            <div class="card-body">
                                <a class="course-btn btn btn-primary" href="/attendance/course/{{ course.slug }}">{{ course.title }}</a>
                            </div>

                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

alpastor/templates/epita/schedule_list.html
{% extends 'base_generic.html' %}

{% load static %}

{% block content %}
    <table class="table text-center">
        <thead class="thead-inverse">
        <tr>
            <th>Active Courses</th>
        </tr>
        </thead>
        <tbody>
        {% for schedule in schedule_list %}
            <tr>
                <th>
                    <a class="btn btn-primary"
                       href="/attendance/course/schedule/?schedule_id={{ schedule.id }}">{{ schedule.date }}</a>
                </th>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}